name: Create Release on Push
on:
  push:
    branches:
      - 1.21 # Or specify other branches like ['main', 'develop']
permissions:
  contents: write # Required to create releases and tags
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Automated release for commit ${{ github.sha }}
          draft: false
          prerelease: false
